/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
    T extends ColumnType<infer S, infer I, infer U>
        ? ColumnType<S, I | undefined, U>
        : ColumnType<T, T | undefined, T>;

// export interface AchievementCategoryData {
//   color: string;
//   icon: string;
//   id: Generated<number>;
//   nameId: number;
//   order: number;
//   parentId: number | null;
//   visibilityCriterion: string | null;
// }

// export interface AchievementCategoryDataAchievementIdsJunction {
//   AchievementCategoryData_id: number | null;
//   target_id: number | null;
// }

// export interface AchievementData {
//   accountLinked: number | null;
//   categoryId: number;
//   descriptionId: number;
//   iconId: number;
//   id: Generated<number>;
//   level: number;
//   nameId: number;
//   order: number | null;
//   points: number;
// }

// export interface AchievementDataObjectiveIdsJunction {
//   AchievementData_id: number | null;
//   target_id: number | null;
// }

// export interface AchievementDataRewardIdsJunction {
//   AchievementData_id: number | null;
//   target_id: number | null;
// }

// export interface AchievementObjectiveData {
//   achievementId: number;
//   criterion: string;
//   id: Generated<number>;
//   nameId: number;
//   order: number | null;
// }

// export interface AchievementRewardData {
//   achievementId: number;
//   alterationsReward: string;
//   criterions: string;
//   emotesReward: string;
//   experienceRatio: number | null;
//   guildPoints: number | null;
//   id: Generated<number>;
//   itemsQuantityReward: string;
//   itemsReward: string;
//   kamasRatio: number | null;
//   kamasScaleWithPlayerLevel: number | null;
//   ornamentsReward: string;
//   spellsReward: string;
//   titlesReward: string;
// }

// export interface ActionFilterData {
//   id: Generated<number>;
//   nameId: number;
//   order: number;
// }

// export interface ActivitySuggestionCategoryData {
//   id: Generated<number>;
//   nameId: number;
//   parentId: number | null;
// }

// export interface ActivitySuggestionData {
//   categoryId: number;
//   descriptionId: number;
//   endDate: number | null;
//   icon: string;
//   id: Generated<number>;
//   isLarge: number | null;
//   level: number;
//   mapId: number;
//   nameId: number;
//   startDate: number | null;
// }

// export interface AlignmentGiftData {
//   id: Generated<number>;
//   nameId: number;
// }

// export interface AlignmentOrderData {
//   id: Generated<number>;
//   nameId: number;
//   sideId: number | null;
// }

// export interface AlignmentRankData {
//   descriptionId: number;
//   id: Generated<number>;
//   minimumAlignment: number | null;
//   nameId: number;
//   orderId: number | null;
// }

// export interface AlignmentRankGiftsData {
//   gifts: string;
//   id: Generated<number>;
// }

// export interface AlignmentSideData {
//   id: Generated<number>;
//   nameId: number;
// }

// export interface AlignmentTitleData {
//   id: string;
//   namesId: string;
//   shortsId: string;
//   sideId: number | null;
// }

// export interface AllianceRankData {
//   gfxId: number;
//   id: Generated<number>;
//   isModifiable: number | null;
//   nameId: number;
//   order: number | null;
// }

// export interface AllianceRankNameSuggestionData {
//   id: string;
//   uiKey: string;
// }

// export interface AllianceRightData {
//   groupId: number;
//   id: Generated<number>;
//   nameId: number;
//   order: number | null;
// }

// export interface AllianceRightGroupData {
//   id: Generated<number>;
//   nameId: number;
//   order: number | null;
//   rights: string;
// }

// export interface AllianceTagData {
//   id: Generated<number>;
//   nameId: number;
//   order: number | null;
//   typeId: number;
// }

// export interface AllianceTagTypeData {
//   id: Generated<number>;
//   nameId: number;
// }

// export interface AlmanaxCalendarData {
//   categoryId: number;
//   celebrationDescriptionId: number | null;
//   celebrationNameId: number | null;
//   dates: string;
//   descId: number;
//   id: Generated<number>;
//   meridiaDescriptionId: number;
//   meridiaEffectId: number;
//   meridiaIllustrationId: number;
//   nameId: number;
//   npcId: number;
//   objectiveId: number;
//   rubrikabraxId: number;
// }

// export interface AlmanaxCalendarDataBonusesIdsJunction {
//   AlmanaxCalendarData_id: number | null;
//   target_id: number | null;
// }

// export interface AlmanaxCategoryData {
//   id: Generated<number>;
//   nameId: number | null;
//   protectorDescriptionId: number | null;
//   protectorIllustrationId: number;
//   protectorNameId: number | null;
// }

// export interface AlmanaxZodiacData {
//   dateEnd: string;
//   dateStart: string;
//   descriptionId: number;
//   id: Generated<number>;
//   nameId: number;
//   picture: string;
// }

// export interface AlterationCategoryData {
//   id: Generated<number>;
//   nameId: number;
//   parentId: number | null;
// }

// export interface AlterationData {
//   categoryId: number;
//   criterions: string;
//   descriptionId: number;
//   iconId: number;
//   id: Generated<number>;
//   isVisible: number;
//   isWebDisplay: number;
//   nameId: number;
//   possibleEffects: string;
// }

// export interface AppearanceData {
//   data: string;
//   id: Generated<number>;
//   type: number;
//   usePlayerLook: number | null;
// }

// export interface AreaData {
//   bounds: string;
//   containHouses: number;
//   containPaddocks: number;
//   hasSuggestion: number;
//   hasWorldMap: number | null;
//   id: Generated<number>;
//   nameId: number;
//   superAreaId: number | null;
//   worldmapId: number | null;
// }

// export interface AreaDataSubareaIdsJunction {
//   AreaData_id: number | null;
//   target_id: number | null;
// }

// export interface ArenaLeagueData {
//   highRatingBound: number;
//   icon: string;
//   id: Generated<number>;
//   illus: string;
//   isLastLeague: number | null;
//   lowRatingBound: number | null;
//   nameId: number;
//   ornamentId: number;
// }

// export interface ArenaLeagueSeasonData {
//   beginning: number;
//   closure: number;
//   flagObjectId: number;
//   id: string;
//   nameId: string;
//   resetDate: number | null;
//   uid: number;
// }

// export interface BonusCriterionData {
//   id: Generated<number>;
//   type: number;
//   value: number;
// }

// export interface BonusData {
//   amount: number;
//   id: Generated<number>;
//   type: number;
// }

// export interface BonusDataCriterionsIdsJunction {
//   BonusData_id: number | null;
//   target_id: number | null;
// }

// export interface BreachBossData {
//   accessCriterion: string;
//   apparitionCriterion: string;
//   category: number;
//   id: Generated<number>;
//   incompatibleBosses: string;
//   monsterId: number;
//   rewardId: number;
// }

// export interface BreachDungeonModificatorData {
//   additionalRewardPercent: number;
//   criterion: string | null;
//   id: Generated<number>;
//   isPositiveForPlayers: number | null;
//   modificatorId: number;
//   score: number;
//   tooltipBaseline: string;
// }

// export interface BreachPrizeData {
//   categoryId: number;
//   descriptionKey: string;
//   id: Generated<number>;
//   nameId: number;
//   tooltipKey: string;
// }

// export interface BreachWorldMapCoordinateData {
//   exploredMapIcon: number;
//   id: string;
//   mapCoordinateX: number;
//   mapCoordinateY: number;
//   mapStage: number;
//   unexploredMapIcon: number;
// }

// export interface BreachWorldMapSectorData {
//   id: Generated<number>;
//   legendId: string;
//   maxStage: number;
//   minStage: number;
//   sectorIcon: string;
//   sectorNameId: string;
// }

// export interface BreedData {
//   breedRoles: string;
//   breedSpellsId: string;
//   complexity: number;
//   creatureBonesId: number;
//   descriptionId: number;
//   femaleColors: string;
//   femaleLook: string;
//   gameplayDescriptionId: string;
//   id: Generated<number>;
//   maleColors: string;
//   maleLook: string;
//   shortNameId: string;
//   sortIndex: number;
//   statsPointsForAgility: string;
//   statsPointsForChance: string;
//   statsPointsForIntelligence: string;
//   statsPointsForStrength: string;
//   statsPointsForVitality: string;
//   statsPointsForWisdom: string;
// }

// export interface BreedRoleData {
//   assetId: number;
//   color: number;
//   descriptionId: number;
//   id: Generated<number>;
//   nameId: number;
// }

// export interface CalendarEventData {
//   categoryId: number;
//   criterion: string | null;
//   descriptionId: number;
//   id: Generated<number>;
//   map: number;
//   nameId: number;
//   picture: string;
//   recommendedLevel: number;
//   rewards: string;
// }

// export interface ChallengeData {
//   activationCriterion: string;
//   categoryId: number;
//   completionCriterion: string;
//   descriptionId: number;
//   iconId: number;
//   id: Generated<number>;
//   incompatibleChallenges: string;
//   nameId: number;
//   targetMonsterId: number | null;
// }

// export interface CharacteristicCategoryData {
//   id: Generated<number>;
//   nameId: number;
//   order: number;
// }

// export interface CharacteristicCategoryDataCharacteristicIdsJunction {
//   CharacteristicCategoryData_id: number | null;
//   target_id: number | null;
// }

// export interface CharacteristicData {
//   asset: string | null;
//   categoryId: number;
//   id: Generated<number>;
//   keyword: string;
//   nameId: number;
//   order: number;
//   scaleFormulaId: number | null;
//   upgradable: number | null;
//   visible: number | null;
// }

// export interface CharacterXpMappingData {
//   experiencePoints: number | null;
//   id: string;
// }

// export interface ChatChannelData {
//   descriptionId: number;
//   id: Generated<number>;
//   isPrivate: number | null;
//   nameId: number;
//   shortcut: string;
// }

// export interface ChoiceData {
//   choiceNameId: number;
//   duration: number;
//   id: Generated<number>;
//   options: string;
// }

// export interface CollectableData {
//   entityId: number;
//   gfxId: number | null;
//   id: string;
//   name: string;
//   order: number;
//   rarity: number;
//   typeId: number;
// }

// export interface CollectionData {
//   collectables: string;
//   criterion: string;
//   id: string;
//   name: string;
//   typeId: number;
// }

// export interface CompanionCharacteristicData {
//   caracId: number;
//   companionId: number;
//   id: Generated<number>;
//   order: number;
//   statPerLevelRange: string;
// }

// export interface CompanionData {
//   assetId: number;
//   characteristics: string;
//   creatureBoneId: number;
//   descriptionId: number;
//   id: Generated<number>;
//   look: string;
//   nameId: number;
//   spells: string;
//   startingSpellLevelId: number;
//   visibility: string | null;
//   webDisplay: number;
// }

// export interface CompanionSpellData {
//   companionId: number;
//   gradeByLevel: string;
//   id: Generated<number>;
//   spellId: number;
// }

// export interface CreatureBoneOverrideData {
//   boneId: number;
//   creatureBoneId: number;
//   id: string;
// }

// export interface CreatureBoneTypeData {
//   creatureBoneId: number;
//   id: Generated<number>;
// }

// export interface CustomModeBreedSpellData {
//   breedId: number;
//   id: Generated<number>;
//   isHidden: number | null;
//   isInitialSpell: number;
//   pairId: number;
// }

// export interface DocumentData {
//   authorId: string;
//   clientProperties: string | null;
//   contentCSS: string;
//   contentId: string;
//   id: Generated<number>;
//   showBackgroundImage: number;
//   showTitle: number;
//   subTitleId: string;
//   titleId: string;
//   typeId: number;
// }

// export interface DungeonData {
//   entranceMapId: number;
//   exitMapId: number;
//   id: Generated<number>;
//   nameId: number;
//   optimalPlayerLevel: number;
// }

// export interface DungeonDataMapIdsJunction {
//   DungeonData_id: number | null;
//   target_id: number | null;
// }

// export interface EffectData {
//   actionFiltersId: string;
//   active: number | null;
//   bonusType: number | null;
//   boost: number | null;
//   category: number;
//   characteristic: number | null;
//   characteristicOperator: string | null;
//   descriptionId: number;
//   effectPowerRate: number | null;
//   effectPriority: number | null;
//   effectTriggerDuration: number | null;
//   elementId: number;
//   forceMinMax: number | null;
//   hideValueInTooltip: number | null;
//   iconId: number | null;
//   id: Generated<number>;
//   isInPercent: number | null;
//   oppositeId: number | null;
//   showInSet: number | null;
//   showInTooltip: number | null;
//   textIconReferenceId: number | null;
//   theoreticalDescriptionId: string;
//   theoreticalPattern: number | null;
//   useDice: number | null;
//   useInFight: number | null;
// }

// export interface EffectInstanceDice {
//   baseEffectId: number;
//   delay: number | null;
//   diceNum: number;
//   diceSide: number;
//   dispellable: number;
//   displayZero: number | null;
//   duration: number | null;
//   effectElement: number;
//   effectId: number;
//   effectTriggerDuration: number | null;
//   effectUid: number | null;
//   group: number | null;
//   id: string;
//   m_flags: number;
//   modificator: number | null;
//   order: number | null;
//   random: number | null;
//   spellId: number;
//   targetId: number | null;
//   targetMask: string | null;
//   triggers: string | null;
//   value: number | null;
//   zoneDescr: string;
// }

// export interface EmblemBackgroundData {
//   id: Generated<number>;
//   order: number;
// }

// export interface EmblemSymbolCategoryData {
//   id: Generated<number>;
//   nameId: number;
// }

// export interface EmblemSymbolData {
//   categoryId: number;
//   colorizable: number;
//   iconId: number;
//   id: Generated<number>;
//   order: number;
//   skinId: number;
// }

// export interface EmoticonData {
//   allowOnMount: number | null;
//   animName: string;
//   aura: number | null;
//   cooldown: number;
//   criterion: string | null;
//   duration: number | null;
//   eightDirections: number | null;
//   id: Generated<number>;
//   nameId: number;
//   order: number;
//   persistancy: number;
//   persistantAnimName: string;
//   scale: number;
//   shortcutId: string;
//   spellLevelId: number | null;
//   weight: number | null;
// }

// export interface EvolutiveEffectData {
//   actionId: number;
//   id: Generated<number>;
//   progressionPerLevelRange: string;
//   targetId: number;
// }

// export interface EvolutiveItemTypeData {
//   experienceBoost: number;
//   experienceByLevel: string;
//   id: Generated<number>;
//   maxLevel: number;
// }

// export interface ExpeditionSeasonData {
//   beginning: number;
//   closure: number;
//   flagObjectId: number;
//   id: string;
//   nameId: string;
//   resetDate: number;
//   uid: number;
// }

// export interface ExternalNotificationData {
//   categoryId: number;
//   colorId: number;
//   defaultEnable: number;
//   defaultMultiAccount: number;
//   defaultNotify: number | null;
//   defaultSound: number;
//   descriptionId: number;
//   iconId: number;
//   id: Generated<number>;
//   messageId: string;
//   name: string;
// }

// export interface FeatureDescriptionData {
//   children: string;
//   criterion: string | null;
//   descriptionId: number;
//   id: Generated<number>;
//   images: string;
//   nameId: number;
//   parentId: number | null;
//   priority: number;
// }

// export interface FightScenarioData {
//   id: Generated<number>;
//   nameId: string;
// }

// export interface ForgettableSpellData {
//   id: Generated<number>;
//   itemId: number;
//   pairId: number;
// }

// export interface GuildChestTabData {
//   cost: number | null;
//   dropRight: number;
//   gfxId: number;
//   id: string;
//   index: number;
//   nameId: number;
//   openRight: number;
//   seniority: number | null;
//   serverType: number;
//   tabId: number;
//   takeRight: number;
// }

// export interface GuildHallData {
//   id: Generated<number>;
//   mapId: number;
//   nameId: number;
//   subareaId: number;
// }

// export interface GuildHallThemeData {
//   id: Generated<number>;
//   nameId: number;
//   order: number | null;
// }

// export interface GuildLevelRewardData {
//   descriptionId: number;
//   id: string;
//   level: number;
//   nameId: number;
//   picto: string;
// }

// export interface GuildMissionActivityData {
//   id: Generated<number>;
//   level: number;
//   nameId: number;
//   recommendedPlayers: number;
//   rerollCost: number;
// }

// export interface GuildMissionActivityDataMilestonesIdsJunction {
//   GuildMissionActivityData_id: number | null;
//   target_id: number | null;
// }

// export interface GuildMissionData {
//   activityPoint: number;
//   categoryId: number;
//   gradeId: number;
//   id: Generated<number>;
//   nameId: number;
//   objectives: string;
//   recommendedLevel: number;
//   superCategoryId: number;
//   token: number;
// }

// export interface GuildMissionGradeData {
//   activityPoint: number;
//   id: Generated<number>;
//   name: string;
//   rankId: number;
//   token: number;
// }

// export interface GuildMissionMilestoneData {
//   acknowledgmentPoint: number;
//   activityId: number;
//   activityPoint: number;
//   id: Generated<number>;
//   milestoneLevel: number;
//   nameId: number;
//   xp: number;
// }

// export interface GuildMissionObjectiveData {
//   activationCriterion: string | null;
//   alterationId: number | null;
//   areaId: number;
//   descriptionId: number;
//   familyId: number | null;
//   familyMonsters: string;
//   id: Generated<number>;
//   inDungeon: number;
//   intensity: number | null;
//   mapId: number;
//   minLevel: number | null;
//   missionId: number;
//   monsterId: number;
//   objectId: number | null;
//   order: number;
//   quantity: number | null;
//   stage: number | null;
//   subareaId: number;
//   superCategoryId: number;
// }

// export interface GuildMissionRankData {
//   grades: string;
//   id: Generated<number>;
//   nameId: number;
// }

// export interface GuildMissionSuperCategoryData {
//   id: Generated<number>;
//   nameId: number;
// }

// export interface GuildRankData {
//   gfxId: number;
//   id: Generated<number>;
//   nameId: number;
//   order: number | null;
// }

// export interface GuildRankNameSuggestionData {
//   id: string;
//   uiKey: string;
// }

// export interface GuildRightData {
//   groupId: number;
//   id: Generated<number>;
//   nameId: number;
//   order: number | null;
// }

// export interface GuildRightGroupData {
//   id: Generated<number>;
//   nameId: number;
//   order: number | null;
//   rights: string;
// }

// export interface GuildShopBoostData {
//   alterationId: number;
//   descriptionId: number;
//   id: Generated<number>;
//   nameId: number;
// }

// export interface GuildTagData {
//   id: Generated<number>;
//   nameId: number;
//   order: number;
//   typeId: number;
// }

// export interface GuildTagTypeData {
//   id: Generated<number>;
//   nameId: number;
// }

// export interface HavenbagFurnitureData {
//   blocksMovement: number;
//   cellsHeight: number;
//   cellsWidth: number;
//   color: number;
//   elementId: number;
//   gfxId: number;
//   height: number | null;
//   horizontalSymmetry: number | null;
//   id: string;
//   isStackable: number | null;
//   layerId: number;
//   order: number | null;
//   origin: string;
//   size: string;
//   skillId: number | null;
//   themeId: number;
//   typeId: number;
// }

// export interface HavenbagThemeData {
//   id: Generated<number>;
//   mapId: number;
//   nameId: number;
// }

// export interface HeadData {
//   assetId: string;
//   breed: number;
//   gender: number | null;
//   id: Generated<number>;
//   label: string;
//   order: number | null;
//   payable: number | null;
//   skins: string;
// }

export interface HintCategoryData {
    id: Generated<number>;
    nameId: number;
}

export interface HintData {
    categoryId: number;
    gfx: number;
    id: Generated<number>;
    level: number | null;
    mapId: number;
    nameId: number;
    outdoor: number | null;
    realMapId: number | null;
    subareaId: number;
    worldMapId: number;
    x: number;
    y: number;
}

// export interface HouseData {
//   defaultPrice: number;
//   descriptionId: number | null;
//   gfxId: number;
//   id: string;
//   nameId: number;
//   roomCount: number;
//   typeId: number;
// }

// export interface InfiniteDreamIntensityData {
//   additionalLife: number;
//   dreamFragments: number;
//   dropBonus: number;
//   droplegend: number | null;
//   id: Generated<number>;
//   intensity: number;
//   money: number;
//   nameId: number;
//   xpBonus: number;
// }

// export interface InfiniteDreamRewardActionData {
//   duration: number;
//   effect: string;
//   id: Generated<number>;
//   isAlly: number;
// }

// export interface InfiniteDreamRewardData {
//   actions: string;
//   descriptionId: number;
//   id: Generated<number>;
//   nameId: number;
// }

// export interface InfoMessageData {
//   id: string;
//   messageId: number | null;
//   textId: number;
//   typeId: number | null;
// }

// export interface InteractiveData {
//   id: Generated<number>;
//   nameId: number;
// }

export interface ItemData {
    appearanceId: number | null;
    craftConditionalCriterion: string | null;
    craftFeasibleCriterion: string;
    craftVisibleCriterion: string;
    craftXpRatio: number;
    criterions: string | null;
    criterionsTarget: string | null;
    descriptionId: number;
    favoriteRecyclingSubareas: string;
    favoriteSubAreas: string;
    favoriteSubAreasBonus: number | null;
    iconId: number;
    id: Generated<number>;
    importantNoticeId: string;
    isColorable: number | null;
    itemSetId: number;
    level: number;
    m_flags: number;
    nameId: number;
    possibleEffects: string;
    price: number;
    realWeight: number;
    recipeSlots: number;
    recyclingNuggets: number | null;
    resourcesBySubarea: string;
    typeId: number;
    visibilityCriterion: string | null;
}

// export interface ItemDataDropMonsterIdsJunction {
//   ItemData_id: number | null;
//   target_id: number | null;
// }

// export interface ItemDataDropTemporisMonsterIdsJunction {
//   ItemData_id: number | null;
//   target_id: number | null;
// }

// export interface ItemDataEvolutiveEffectIdsJunction {
//   ItemData_id: number | null;
//   target_id: number | null;
// }

// export interface ItemDataRecipeIdsJunction {
//   ItemData_id: number | null;
//   target_id: number | null;
// }

// export interface ItemSetData {
//   bonusIsSecret: number | null;
//   effects: string;
//   id: Generated<number>;
//   isCosmetic: number | null;
//   items: string;
//   nameId: number;
// }

// export interface ItemSuperTypeData {
//   id: Generated<number>;
//   possiblePositions: string;
// }

// export interface ItemTypeData {
//   categoryId: number | null;
//   craftXpRatio: number;
//   evolutiveTypeId: number | null;
//   id: Generated<number>;
//   isInEncyclopedia: number;
//   nameId: number;
//   rawZone: string | null;
//   superTypeId: number;
// }

export interface JobData {
    hasLegendaryCraft: number | null;
    iconId: number;
    id: Generated<number>;
    nameId: number;
}

// export interface KothRoleData {
//   id: Generated<number>;
//   isDefault: number | null;
//   nameId: number;
// }

// export interface LegendaryPowerCategoryData {
//   categoryName: string;
//   categoryOverridable: number;
//   categorySpells: string;
//   id: Generated<number>;
// }

// export interface LegendaryTreasureHuntData {
//   chestId: number;
//   id: Generated<number>;
//   level: number;
//   mapItemId: number;
//   monsterId: number;
//   nameId: number;
//   xpRatio: number;
// }

// export interface LivingObjectSkinMoodsData {
//   id: string;
//   moods: string;
//   skinId: number;
// }

// export interface LuaFormulaData {
//   formula: string;
//   id: string;
// }

export interface MapInformationData {
    id: Generated<number>;
    m_flags: number;
    nameId: number | null;
    posX: number;
    posY: number;
    subAreaId: number;
    tacticalModeTemplateId: number | null;
    worldMap: number;
}

// export interface MapReferenceData {
//   cellId: number;
//   id: Generated<number>;
//   mapId: number;
// }

export interface MapsCoordinateData {
    compressedCoords: number;
    id: string;
}

export interface MapsCoordinateDataMapIdsJunction {
    MapsCoordinateData_id: number | null;
    target_id: number | null;
}

// export interface MapScrollActionData {
//   bottomExists: number;
//   bottomMapId: number;
//   id: Generated<number>;
//   leftExists: number;
//   leftMapId: number;
//   rightExists: number;
//   rightMapId: number;
//   topExists: number;
//   topMapId: number;
// }

// export interface ModsterData {
//   id: Generated<number>;
//   itemId: number;
//   modsterAchievements: string;
//   modsterActiveSpells: string;
//   modsterHiddenAchievements: string;
//   modsterId: number;
//   modsterPassiveSpells: string;
//   order: number | null;
//   parentsModsterId: string;
// }

// export interface MonsterData {
//   aggressiveAttackDelay: number;
//   aggressiveImmunityCriterion: string;
//   aggressiveLevelDiff: number;
//   aggressiveZoneSize: number;
//   animFunList: string;
//   characRatios: string;
//   correspondingMiniBossId: number;
//   creatureBoneId: number | null;
//   drops: string;
//   favoriteSubareaId: number | null;
//   gfxId: number;
//   grades: string;
//   id: Generated<number>;
//   incompatibleChallenges: string;
//   incompatibleIdols: string;
//   look: string;
//   m_flags: number;
//   nameId: number;
//   race: number;
//   scaleGradeRef: number;
//   speedAdjust: number;
//   spellGrades: string;
//   spells: string;
//   subareas: string;
//   summonCost: number;
//   temporisDrops: string;
// }

// export interface MonsterMiniBossData {
//   id: Generated<number>;
//   monsterReplacingId: number;
// }

// export interface MonsterRaceData {
//   aggressiveAttackDelay: number | null;
//   aggressiveImmunityCriterion: string | null;
//   aggressiveLevelDiff: number | null;
//   aggressiveZoneSize: number | null;
//   id: Generated<number>;
//   monsters: string;
//   nameId: number;
//   superRaceId: number;
// }

// export interface MonsterSuperRaceData {
//   id: Generated<number>;
//   nameId: number;
// }

// export interface MonthData {
//   id: string;
//   nameId: number;
// }

// export interface MountBehaviorData {
//   descriptionId: number;
//   id: Generated<number>;
//   nameId: number;
// }

// export interface MountBoneData {
//   id: Generated<number>;
// }

// export interface MountData {
//   certificateId: number;
//   effects: string;
//   familyId: number;
//   id: Generated<number>;
//   look: string;
//   nameId: number;
// }

// export interface MountFamilyData {
//   headUri: string;
//   id: Generated<number>;
//   nameId: number;
// }

// export interface NamingRuleData {
//   id: Generated<number>;
//   maxLength: number;
//   minLength: number;
//   regexp: string;
// }

// export interface NotificationData {
//   cantBeClosed: number | null;
//   iconId: number | null;
//   id: Generated<number>;
//   messageId: string;
//   titleId: string;
//   trigger: string | null;
//   typeId: number;
// }

// export interface NpcActionData {
//   id: Generated<number>;
//   nameId: number;
//   realId: number;
// }

// export interface NpcData {
//   actions: string;
//   animFunList: string;
//   defaultSkinId: number;
//   dialogData: string;
//   dialogMessages: string;
//   dialogReplies: string;
//   fastAnimsFun: number | null;
//   gender: number | null;
//   id: Generated<number>;
//   look: string;
//   nameId: number;
//   tooltipVisible: number;
// }

// export interface NpcDialogSkinData {
//   backgroundColor: string;
//   borderColor: string | null;
//   buttonsColorTypes: number;
//   fontColor: string;
//   gfxId: number;
//   hasHalo: number | null;
//   headerColor: string;
//   headerDecorationColor: string;
//   headerDecorationGfxId: number;
//   headerFontColor: string;
//   headerGfxId: number;
//   headerOrnamentColor: string;
//   headerOrnamentGfxId: number;
//   id: Generated<number>;
//   isBold: number | null;
// }

// export interface NpcMessageData {
//   id: Generated<number>;
//   messageBubblePosition: number;
//   messageId: string;
//   messageNpcMoodId: number;
//   messageParams: string;
//   messageSkinId: number;
// }

// export interface OptionalFeatureData {
//   activationCriterions: string | null;
//   id: Generated<number>;
//   isActivationOnLaunch: number | null;
//   isActivationOnServerConnection: number | null;
//   isClient: number;
//   isServer: number;
//   keyword: string;
// }

// export interface OrnamentData {
//   assetId: number;
//   iconId: number | null;
//   id: Generated<number>;
//   nameId: number;
//   order: number;
//   visible: number;
// }

// export interface PointOfInterestData {
//   id: Generated<number>;
//   nameId: number;
// }

// export interface PopupInformationData {
//   autoTrigger: number;
//   buttons: string;
//   cacheType: number;
//   criterion: string;
//   descriptionId: number;
//   headerId: string;
//   id: Generated<number>;
//   illuName: string;
//   parentId: number;
//   titleId: string;
// }

// export interface PresetIconData {
//   id: Generated<number>;
// }

// export interface ProgressingAchievementSeasonData {
//   id: Generated<number>;
//   name: string;
//   seasonId: number;
// }

// export interface ProgressingAchievementStepData {
//   achievementId: number;
//   id: Generated<number>;
//   isBuyable: number | null;
//   isCosmetic: number;
//   progressId: number;
//   score: number;
// }

// export interface QuestCategoryData {
//   id: Generated<number>;
//   nameId: number;
//   order: number;
// }

// export interface QuestCategoryDataQuestIdsJunction {
//   QuestCategoryData_id: number | null;
//   target_id: number | null;
// }

// export interface QuestData {
//   categoryId: number;
//   followable: number;
//   id: Generated<number>;
//   isDungeonQuest: number | null;
//   isEvent: number | null;
//   isPartyQuest: number | null;
//   levelMax: number;
//   levelMin: number;
//   nameId: number;
//   repeatLimit: number;
//   repeatType: number;
//   startCriterion: string;
// }

// export interface QuestDataStepIdsJunction {
//   QuestData_id: number | null;
//   target_id: number | null;
// }

// export interface QuestObjectiveBringItemToNpcData {
//   coords: string;
//   dialogId: number | null;
//   id: Generated<number>;
//   mapId: number;
//   parameters: string;
//   stepId: number;
//   typeId: number;
// }

// export interface QuestObjectiveBringSoulToNpcData {
//   coords: string;
//   dialogId: number | null;
//   id: Generated<number>;
//   mapId: number;
//   parameters: string;
//   stepId: number;
//   typeId: number;
// }

// export interface QuestObjectiveCraftItemData {
//   coords: string;
//   dialogId: number;
//   id: Generated<number>;
//   mapId: number | null;
//   parameters: string;
//   stepId: number;
//   typeId: number;
// }

// export interface QuestObjectiveDiscoverMapData {
//   coords: string;
//   dialogId: number | null;
//   id: Generated<number>;
//   mapId: number | null;
//   parameters: string;
//   stepId: number;
//   typeId: number;
// }

// export interface QuestObjectiveDiscoverSubAreaData {
//   coords: string;
//   dialogId: number | null;
//   id: Generated<number>;
//   mapId: number | null;
//   parameters: string;
//   stepId: number;
//   typeId: number;
// }

// export interface QuestObjectiveFightMonsterData {
//   coords: string;
//   dialogId: number | null;
//   id: Generated<number>;
//   mapId: number | null;
//   parameters: string;
//   stepId: number;
//   typeId: number;
// }

// export interface QuestObjectiveFightMonstersOnMapData {
//   coords: string;
//   dialogId: number | null;
//   id: Generated<number>;
//   mapId: number;
//   parameters: string;
//   stepId: number;
//   typeId: number;
// }

// export interface QuestObjectiveFreeFormData {
//   coords: string;
//   dialogId: number | null;
//   id: Generated<number>;
//   mapId: number;
//   parameters: string;
//   stepId: number;
//   typeId: number;
// }

// export interface QuestObjectiveGoToNpcData {
//   coords: string;
//   dialogId: number | null;
//   id: Generated<number>;
//   mapId: number;
//   parameters: string;
//   stepId: number;
//   typeId: number;
// }

// export interface QuestObjectiveMultiFightMonsterData {
//   coords: string;
//   dialogId: number | null;
//   id: Generated<number>;
//   mapId: number | null;
//   parameters: string;
//   stepId: number;
//   typeId: number;
// }

// export interface QuestObjectiveTypeData {
//   id: Generated<number>;
//   nameId: number;
// }

// export interface QuestStepData {
//   descriptionId: number;
//   dialogId: number;
//   duration: number;
//   id: Generated<number>;
//   nameId: number;
//   optimalLevel: number;
//   questId: number;
// }

// export interface QuestStepDataObjectiveIdsJunction {
//   QuestStepData_id: number | null;
//   target_id: number | null;
// }

// export interface QuestStepDataRewardsIdsJunction {
//   QuestStepData_id: number | null;
//   target_id: number | null;
// }

// export interface QuestStepRewardData {
//   emotesReward: string;
//   experienceRatio: number;
//   id: Generated<number>;
//   itemsReward: string;
//   jobsReward: string;
//   kamasRatio: number;
//   kamasScaleWithPlayerLevel: number | null;
//   levelMax: number;
//   levelMin: number;
//   spellsReward: string;
//   stepId: number;
//   titlesReward: string;
// }

// export interface RandomDropGroupData {
//   displayChances: number | null;
//   id: Generated<number>;
//   randomDropItems: string;
// }

export interface RecipeData {
    id: string;
    jobId: number;
    quantities: string;
    resultId: number;
    resultLevel: number;
    resultNameId: string;
    resultTypeId: number;
    skillId: number;
}

export interface RecipeDataIngredientIdsJunction {
    RecipeData_id: number | null;
    target_id: number | null;
}

// export interface RideFoodData {
//   familyId: number;
//   gid: number;
//   id: string;
//   typeId: number | null;
// }

// export interface RiderBoneData {
//   id: Generated<number>;
// }

// export interface ServerCommunityData {
//   defaultCountries: string;
//   id: Generated<number>;
//   nameId: number | null;
//   namingRuleAdminId: number | null;
//   namingRuleAllianceNameId: number;
//   namingRuleAllianceTagId: number;
//   namingRuleGuildNameId: number;
//   namingRuleModoId: number | null;
//   namingRuleMountNameId: number;
//   namingRuleNameGeneratorId: number | null;
//   namingRulePartyNameId: number | null;
//   namingRulePlayerNameId: number;
//   namingRulePresetNameId: number;
//   shortId: string;
// }

// export interface ServerCommunityDataSupportedLangIdsJunction {
//   ServerCommunityData_id: number | null;
//   target_id: number | null;
// }

// export interface ServerData {
//   commentId: string;
//   communityId: number;
//   gameTypeId: number;
//   id: Generated<number>;
//   illus: string;
//   language: string;
//   monoAccount: number | null;
//   nameId: number;
//   populationId: number | null;
// }

// export interface ServerGameTypeData {
//   descriptionId: number;
//   id: Generated<number>;
//   nameId: number;
//   rulesId: number;
//   selectableByPlayer: number;
// }

// export interface ServerLangData {
//   id: Generated<number>;
//   langCode: string;
//   nameId: number;
// }

// export interface ServerPopulationData {
//   id: Generated<number>;
//   nameId: number;
//   weight: number;
// }

// export interface ServerSeasonData {
//   beginning: number;
//   closure: number;
//   flagObjectId: number;
//   id: string;
//   nameId: string;
//   resetDate: number;
//   uid: number;
// }

// export interface SignsData {
//   id: string;
//   signs: string;
// }

export interface SkillData {
    allowMarking: number | null;
    availableInHouse: number | null;
    clientDisplay: number;
    cursor: number;
    elementActionId: number;
    gatheredRessourceItem: number;
    id: Generated<number>;
    isForgemagus: number | null;
    levelMin: number;
    nameId: number;
    parentJobId: number;
    range: number;
    useAnimation: string;
    useRangeInClient: number | null;
}

// export interface SkillDataCraftableItemIdsJunction {
//   SkillData_id: number | null;
//   target_id: number | null;
// }

// export interface SkillDataModifiableItemTypeIdsJunction {
//   SkillData_id: number | null;
//   target_id: number | null;
// }

// export interface SkillNameData {
//   id: Generated<number>;
//   nameId: number;
// }

// export interface SkinMappingData {
//   id: Generated<number>;
//   lowDefId: number;
// }

// export interface SkinSlotRuleData {
//   id: string;
//   skinId: number | null;
//   slotRulesList: string;
// }

// export interface SmileyData {
//   categoryId: number;
//   forPlayers: number;
//   gfxId: string;
//   id: Generated<number>;
//   order: number;
//   referenceId: number | null;
// }

// export interface SmileyPackData {
//   id: Generated<number>;
//   nameId: number;
//   order: number | null;
//   smileys: string;
// }

// export interface SocialRightData {
//   groupId: number;
//   id: Generated<number>;
//   nameId: number;
//   order: number | null;
// }

// export interface SoundBoneData {
//   animSounds: string;
//   id: string;
// }

// export interface SpeakingItemTextData {
//   id: string;
//   textId: number;
//   textLevel: number | null;
//   textProba: number;
//   textRestriction: string | null;
//   textSound: number | null;
//   textStringId: string;
// }

// export interface SpeakingItemTriggerData {
//   id: string;
// }

// export interface SpeakingItemTriggerDataTextIdsJunction {
//   SpeakingItemTriggerData_id: number | null;
//   target_id: number | null;
// }

// export interface SpellBombData {
//   chainReactionSpellId: number;
//   comboCoeff: number;
//   explodSpellId: number;
//   id: Generated<number>;
//   instantSpellId: number;
//   wallId: number;
// }

// export interface SpellData {
//   adminName: string | null;
//   basePreviewZoneDescr: string;
//   boundScriptUsageData: string;
//   criticalHitBoundScriptUsageData: string;
//   descriptionId: number;
//   iconId: number | null;
//   id: Generated<number>;
//   m_flags: number;
//   nameId: number;
//   order: number | null;
//   scriptId: number | null;
//   scriptIdCritical: number | null;
//   scriptParams: string | null;
//   scriptParamsCritical: string | null;
//   spellLevels: string;
//   typeId: number;
// }

// export interface SpellLevelData {
//   apCost: number;
//   criticalEffect: string;
//   criticalHitProbability: number;
//   effects: string;
//   globalCooldown: number | null;
//   grade: number;
//   id: Generated<number>;
//   initialCooldown: number | null;
//   m_flags: number;
//   maxCastPerTarget: number;
//   maxCastPerTurn: number | null;
//   maxStack: number | null;
//   minCastInterval: number | null;
//   minPlayerLevel: number | null;
//   minRange: number;
//   previewZones: string;
//   range: number;
//   spellBreed: number;
//   spellId: number;
//   statesCriterion: string | null;
// }

// export interface SpellPairData {
//   descriptionId: number;
//   iconId: number;
//   id: Generated<number>;
//   nameId: number;
// }

// export interface SpellScriptData {
//   id: string;
//   rawParams: string;
//   type: number;
// }

// export interface SpellStateData {
//   cantBeMoved: number | null;
//   cantBePushed: number | null;
//   cantBeTackled: number | null;
//   cantDealDamage: number | null;
//   cantSwitchPosition: number | null;
//   cantTackle: number | null;
//   displayTurnRemaining: number | null;
//   icon: string | null;
//   iconVisibilityMask: number | null;
//   id: Generated<number>;
//   incurable: number | null;
//   invulnerable: number | null;
//   invulnerableMelee: number | null;
//   invulnerableRange: number | null;
//   isMainState: number | null;
//   isSilent: number | null;
//   nameId: number;
//   preventsFight: number | null;
//   preventsSpellCast: number | null;
// }

// export interface SpellStateDataEffectsIdsJunction {
//   SpellStateData_id: number | null;
//   target_id: number | null;
// }

// export interface SpellTypeData {
//   id: Generated<number>;
//   longNameId: string;
//   shortNameId: string;
// }

// export interface SpellVariantData {
//   breedId: number;
//   id: Generated<number>;
// }

// export interface SpellVariantDataSpellIdsJunction {
//   SpellVariantData_id: number | null;
//   target_id: number | null;
// }

// export interface StealthBoneData {
//   id: Generated<number>;
// }

// export interface SubAreaData {
//   achievements: string;
//   areaId: number | null;
//   associatedZaapMapId: number;
//   basicAccountAllowed: number | null;
//   bounds: string;
//   capturable: number;
//   customWorldMapId: number;
//   displayOnWorldMap: number;
//   dungeonId: number;
//   exploreAchievementId: number | null;
//   harvestables: string;
//   id: Generated<number>;
//   isConquestVillage: number | null;
//   level: number;
//   monsters: string;
//   mountAutoTripAllowed: number;
//   nameId: number;
//   neighbors: string;
//   packId: number;
//   psiAllowed: number;
//   shape: string;
// }

// export interface SubAreaDataEntranceMapIdsJunction {
//   SubAreaData_id: number | null;
//   target_id: number | null;
// }

// export interface SubAreaDataExitMapIdsJunction {
//   SubAreaData_id: number | null;
//   target_id: number | null;
// }

// export interface SubAreaDataMapIdsJunction {
//   SubAreaData_id: number | null;
//   target_id: number | null;
// }

// export interface SuperAreaData {
//   hasWorldMap: number;
//   id: Generated<number>;
//   nameId: number;
//   worldmapId: number;
// }

// export interface TaxCollectorFirstnameData {
//   firstnameId: string;
//   id: Generated<number>;
// }

// export interface TaxCollectorNameData {
//   id: Generated<number>;
//   nameId: number;
// }

// export interface TextIconReferenceData {
//   id: string;
//   referenceKey: string;
// }

// export interface TitleCategoryData {
//   id: Generated<number>;
//   nameId: number;
// }

// export interface TitleData {
//   categoryId: number;
//   id: Generated<number>;
//   nameFemaleId: string;
//   nameMaleId: string;
//   visible: number | null;
// }

export interface Translations {
    id: string | null;
    lang: string | null;
    value: string | null;
}

// export interface VeteranRewardData {
//   id: Generated<number>;
//   itemGID: number;
//   itemQuantity: number;
//   requiredSubDays: number;
// }

// export interface WaypointData {
//   activated: number;
//   id: Generated<number>;
//   mapId: number;
//   subAreaId: number;
// }

// export interface WeaponData {
//   apCost: number;
//   appearanceId: number | null;
//   castInDiagonal: number | null;
//   castInLine: number | null;
//   castTestLos: number;
//   craftConditionalCriterion: string | null;
//   craftFeasibleCriterion: string;
//   craftVisibleCriterion: string;
//   craftXpRatio: number;
//   criterions: string | null;
//   criterionsTarget: string | null;
//   criticalHitBonus: number;
//   criticalHitProbability: number;
//   descriptionId: number;
//   favoriteRecyclingSubareas: string;
//   favoriteSubAreas: string;
//   favoriteSubAreasBonus: number | null;
//   iconId: number;
//   id: Generated<number>;
//   importantNoticeId: string;
//   isColorable: number | null;
//   itemSetId: number;
//   level: number;
//   m_flags: number;
//   maxCastPerTurn: number;
//   minRange: number;
//   nameId: number;
//   possibleEffects: string;
//   price: number;
//   range: number;
//   realWeight: number;
//   recipeSlots: number;
//   recyclingNuggets: number | null;
//   resourcesBySubarea: string;
//   typeId: number;
//   visibilityCriterion: string | null;
// }

// export interface WeaponDataDropMonsterIdsJunction {
//   target_id: number | null;
//   WeaponData_id: number | null;
// }

// export interface WeaponDataDropTemporisMonsterIdsJunction {
//   target_id: number | null;
//   WeaponData_id: number | null;
// }

// export interface WeaponDataEvolutiveEffectIdsJunction {
//   target_id: number | null;
//   WeaponData_id: number | null;
// }

// export interface WeaponDataRecipeIdsJunction {
//   target_id: number | null;
//   WeaponData_id: number | null;
// }

// export interface WorldEventData {
//   areas: string;
//   categoryId: number;
//   deletedObjects: string;
//   descriptionId: number | null;
//   dungeonHunterGroupsPerMap: number;
//   duration: number | null;
//   endMsgId: number | null;
//   fightScenarios: string;
//   globalDrops: string;
//   id: Generated<number>;
//   level: number;
//   monsterHunterGroupsPerMap: number;
//   nameId: number;
//   preMsgDelay: number | null;
//   preMsgId: number | null;
//   startMsgId: number | null;
//   subareas: string;
//   worldEventDataType: number;
//   worldEventEventId: number;
//   worldEventRewardId: number | null;
// }

// export interface WorldEventDungeonData {
//   dungeonId: number;
//   dungeonMapIdTeleport: number;
//   id: string;
//   scoreGroupShared: number;
//   scorePerDamage: number | null;
//   scorePerDungeon: number;
// }

// export interface WorldEventFarmingSimulatorData {
//   id: string;
//   scorePerHarvest: number;
// }

// export interface WorldEventMonstersHunterData {
//   areaList: string;
//   criterion: string | null;
//   id: string;
//   mapList: string;
//   monsterList: string;
//   scoreGroupShared: number | null;
//   scorePerDamage: number | null;
//   scorePerMonster: number;
//   subareaList: string;
// }

// export interface WorldEventRewardData {
//   criterions: string | null;
//   emotes: string | null;
//   experience: number;
//   gameaction: number | null;
//   guildPoints: number | null;
//   id: string;
//   isForTeam: number;
//   kamas: number | null;
//   objects: string;
//   order: number;
//   ornaments: string | null;
//   rankingConditions: string;
//   spells: string | null;
//   titles: string | null;
//   worldEventRewardId: number;
// }

// export interface WorldEventWorldBossesData {
//   areaList: string;
//   criterion: string | null;
//   id: string;
//   mapList: string;
//   monsterList: string;
//   scoreDayCount: number;
//   scoreGroupShared: number;
//   scorePerDamage: number;
//   scoreRatio: number;
//   scoreTotal: number;
//   subareaList: string;
// }

export interface WorldMapData {
    id: Generated<number>;
    mapHeight: number;
    mapWidth: number;
    maxScale: number;
    minScale: number;
    nameId: number;
    origineX: number;
    origineY: number;
    startScale: number;
    totalHeight: number;
    totalWidth: number;
    visibleOnMap: number;
    zoom: string;
}

export interface DB {
    // AchievementCategoryData: AchievementCategoryData;
    // AchievementCategoryData_achievementIds_junction: AchievementCategoryDataAchievementIdsJunction;
    // AchievementData: AchievementData;
    // AchievementData_objectiveIds_junction: AchievementDataObjectiveIdsJunction;
    // AchievementData_rewardIds_junction: AchievementDataRewardIdsJunction;
    // AchievementObjectiveData: AchievementObjectiveData;
    // AchievementRewardData: AchievementRewardData;
    // ActionFilterData: ActionFilterData;
    // ActivitySuggestionCategoryData: ActivitySuggestionCategoryData;
    // ActivitySuggestionData: ActivitySuggestionData;
    // AlignmentGiftData: AlignmentGiftData;
    // AlignmentOrderData: AlignmentOrderData;
    // AlignmentRankData: AlignmentRankData;
    // AlignmentRankGiftsData: AlignmentRankGiftsData;
    // AlignmentSideData: AlignmentSideData;
    // AlignmentTitleData: AlignmentTitleData;
    // AllianceRankData: AllianceRankData;
    // AllianceRankNameSuggestionData: AllianceRankNameSuggestionData;
    // AllianceRightData: AllianceRightData;
    // AllianceRightGroupData: AllianceRightGroupData;
    // AllianceTagData: AllianceTagData;
    // AllianceTagTypeData: AllianceTagTypeData;
    // AlmanaxCalendarData: AlmanaxCalendarData;
    // AlmanaxCalendarData_bonusesIds_junction: AlmanaxCalendarDataBonusesIdsJunction;
    // AlmanaxCategoryData: AlmanaxCategoryData;
    // AlmanaxZodiacData: AlmanaxZodiacData;
    // AlterationCategoryData: AlterationCategoryData;
    // AlterationData: AlterationData;
    // AppearanceData: AppearanceData;
    // AreaData: AreaData;
    // AreaData_subareaIds_junction: AreaDataSubareaIdsJunction;
    // ArenaLeagueData: ArenaLeagueData;
    // ArenaLeagueSeasonData: ArenaLeagueSeasonData;
    // BonusCriterionData: BonusCriterionData;
    // BonusData: BonusData;
    // BonusData_criterionsIds_junction: BonusDataCriterionsIdsJunction;
    // BreachBossData: BreachBossData;
    // BreachDungeonModificatorData: BreachDungeonModificatorData;
    // BreachPrizeData: BreachPrizeData;
    // BreachWorldMapCoordinateData: BreachWorldMapCoordinateData;
    // BreachWorldMapSectorData: BreachWorldMapSectorData;
    // BreedData: BreedData;
    // BreedRoleData: BreedRoleData;
    // CalendarEventData: CalendarEventData;
    // ChallengeData: ChallengeData;
    // CharacteristicCategoryData: CharacteristicCategoryData;
    // CharacteristicCategoryData_characteristicIds_junction: CharacteristicCategoryDataCharacteristicIdsJunction;
    // CharacteristicData: CharacteristicData;
    // CharacterXpMappingData: CharacterXpMappingData;
    // ChatChannelData: ChatChannelData;
    // ChoiceData: ChoiceData;
    // CollectableData: CollectableData;
    // CollectionData: CollectionData;
    // CompanionCharacteristicData: CompanionCharacteristicData;
    // CompanionData: CompanionData;
    // CompanionSpellData: CompanionSpellData;
    // CreatureBoneOverrideData: CreatureBoneOverrideData;
    // CreatureBoneTypeData: CreatureBoneTypeData;
    // CustomModeBreedSpellData: CustomModeBreedSpellData;
    // DocumentData: DocumentData;
    // DungeonData: DungeonData;
    // DungeonData_mapIds_junction: DungeonDataMapIdsJunction;
    // EffectData: EffectData;
    // EffectInstanceDice: EffectInstanceDice;
    // EmblemBackgroundData: EmblemBackgroundData;
    // EmblemSymbolCategoryData: EmblemSymbolCategoryData;
    // EmblemSymbolData: EmblemSymbolData;
    // EmoticonData: EmoticonData;
    // EvolutiveEffectData: EvolutiveEffectData;
    // EvolutiveItemTypeData: EvolutiveItemTypeData;
    // ExpeditionSeasonData: ExpeditionSeasonData;
    // ExternalNotificationData: ExternalNotificationData;
    // FeatureDescriptionData: FeatureDescriptionData;
    // FightScenarioData: FightScenarioData;
    // ForgettableSpellData: ForgettableSpellData;
    // GuildChestTabData: GuildChestTabData;
    // GuildHallData: GuildHallData;
    // GuildHallThemeData: GuildHallThemeData;
    // GuildLevelRewardData: GuildLevelRewardData;
    // GuildMissionActivityData: GuildMissionActivityData;
    // GuildMissionActivityData_milestonesIds_junction: GuildMissionActivityDataMilestonesIdsJunction;
    // GuildMissionData: GuildMissionData;
    // GuildMissionGradeData: GuildMissionGradeData;
    // GuildMissionMilestoneData: GuildMissionMilestoneData;
    // GuildMissionObjectiveData: GuildMissionObjectiveData;
    // GuildMissionRankData: GuildMissionRankData;
    // GuildMissionSuperCategoryData: GuildMissionSuperCategoryData;
    // GuildRankData: GuildRankData;
    // GuildRankNameSuggestionData: GuildRankNameSuggestionData;
    // GuildRightData: GuildRightData;
    // GuildRightGroupData: GuildRightGroupData;
    // GuildShopBoostData: GuildShopBoostData;
    // GuildTagData: GuildTagData;
    // GuildTagTypeData: GuildTagTypeData;
    // HavenbagFurnitureData: HavenbagFurnitureData;
    // HavenbagThemeData: HavenbagThemeData;
    // HeadData: HeadData;
    HintCategoryData: HintCategoryData;
    HintData: HintData;
    // HouseData: HouseData;
    // InfiniteDreamIntensityData: InfiniteDreamIntensityData;
    // InfiniteDreamRewardActionData: InfiniteDreamRewardActionData;
    // InfiniteDreamRewardData: InfiniteDreamRewardData;
    // InfoMessageData: InfoMessageData;
    // InteractiveData: InteractiveData;
    ItemData: ItemData;
    // ItemData_dropTemporisMonsterIds_junction: ItemDataDropTemporisMonsterIdsJunction;
    // ItemData_evolutiveEffectIds_junction: ItemDataEvolutiveEffectIdsJunction;
    // ItemData_recipeIds_junction: ItemDataRecipeIdsJunction;
    // ItemSetData: ItemSetData;
    // ItemSuperTypeData: ItemSuperTypeData;
    // ItemTypeData: ItemTypeData;
    JobData: JobData;
    // KothRoleData: KothRoleData;
    // LegendaryPowerCategoryData: LegendaryPowerCategoryData;
    // LegendaryTreasureHuntData: LegendaryTreasureHuntData;
    // LivingObjectSkinMoodsData: LivingObjectSkinMoodsData;
    // LuaFormulaData: LuaFormulaData;
    MapInformationData: MapInformationData;
    // MapReferenceData: MapReferenceData;
    MapsCoordinateData: MapsCoordinateData;
    MapsCoordinateData_mapIds_junction: MapsCoordinateDataMapIdsJunction;
    // MapScrollActionData: MapScrollActionData;
    // ModsterData: ModsterData;
    // MonsterData: MonsterData;
    // MonsterMiniBossData: MonsterMiniBossData;
    // MonsterRaceData: MonsterRaceData;
    // MonsterSuperRaceData: MonsterSuperRaceData;
    // MonthData: MonthData;
    // MountBehaviorData: MountBehaviorData;
    // MountBoneData: MountBoneData;
    // MountData: MountData;
    // MountFamilyData: MountFamilyData;
    // NamingRuleData: NamingRuleData;
    // NotificationData: NotificationData;
    // NpcActionData: NpcActionData;
    // NpcData: NpcData;
    // NpcDialogSkinData: NpcDialogSkinData;
    // NpcMessageData: NpcMessageData;
    // OptionalFeatureData: OptionalFeatureData;
    // OrnamentData: OrnamentData;
    // PointOfInterestData: PointOfInterestData;
    // PopupInformationData: PopupInformationData;
    // PresetIconData: PresetIconData;
    // ProgressingAchievementSeasonData: ProgressingAchievementSeasonData;
    // ProgressingAchievementStepData: ProgressingAchievementStepData;
    // QuestCategoryData: QuestCategoryData;
    // QuestCategoryData_questIds_junction: QuestCategoryDataQuestIdsJunction;
    // QuestData: QuestData;
    // QuestData_stepIds_junction: QuestDataStepIdsJunction;
    // QuestObjectiveBringItemToNpcData: QuestObjectiveBringItemToNpcData;
    // QuestObjectiveBringSoulToNpcData: QuestObjectiveBringSoulToNpcData;
    // QuestObjectiveCraftItemData: QuestObjectiveCraftItemData;
    // QuestObjectiveDiscoverMapData: QuestObjectiveDiscoverMapData;
    // QuestObjectiveDiscoverSubAreaData: QuestObjectiveDiscoverSubAreaData;
    // QuestObjectiveFightMonsterData: QuestObjectiveFightMonsterData;
    // QuestObjectiveFightMonstersOnMapData: QuestObjectiveFightMonstersOnMapData;
    // QuestObjectiveFreeFormData: QuestObjectiveFreeFormData;
    // QuestObjectiveGoToNpcData: QuestObjectiveGoToNpcData;
    // QuestObjectiveMultiFightMonsterData: QuestObjectiveMultiFightMonsterData;
    // QuestObjectiveTypeData: QuestObjectiveTypeData;
    // QuestStepData: QuestStepData;
    // QuestStepData_objectiveIds_junction: QuestStepDataObjectiveIdsJunction;
    // QuestStepData_rewardsIds_junction: QuestStepDataRewardsIdsJunction;
    // QuestStepRewardData: QuestStepRewardData;
    // RandomDropGroupData: RandomDropGroupData;
    RecipeData: RecipeData;
    RecipeData_ingredientIds_junction: RecipeDataIngredientIdsJunction;
    // RideFoodData: RideFoodData;
    // RiderBoneData: RiderBoneData;
    // ServerCommunityData: ServerCommunityData;
    // ServerCommunityData_supportedLangIds_junction: ServerCommunityDataSupportedLangIdsJunction;
    // ServerData: ServerData;
    // ServerGameTypeData: ServerGameTypeData;
    // ServerLangData: ServerLangData;
    // ServerPopulationData: ServerPopulationData;
    // ServerSeasonData: ServerSeasonData;
    // SignsData: SignsData;
    SkillData: SkillData;
    // SkillData_craftableItemIds_junction: SkillDataCraftableItemIdsJunction;
    // SkillData_modifiableItemTypeIds_junction: SkillDataModifiableItemTypeIdsJunction;
    // SkillNameData: SkillNameData;
    // SkinMappingData: SkinMappingData;
    // SkinSlotRuleData: SkinSlotRuleData;
    // SmileyData: SmileyData;
    // SmileyPackData: SmileyPackData;
    // SocialRightData: SocialRightData;
    // SoundBoneData: SoundBoneData;
    // SpeakingItemTextData: SpeakingItemTextData;
    // SpeakingItemTriggerData: SpeakingItemTriggerData;
    // SpeakingItemTriggerData_textIds_junction: SpeakingItemTriggerDataTextIdsJunction;
    // SpellBombData: SpellBombData;
    // SpellData: SpellData;
    // SpellLevelData: SpellLevelData;
    // SpellPairData: SpellPairData;
    // SpellScriptData: SpellScriptData;
    // SpellStateData: SpellStateData;
    // SpellStateData_effectsIds_junction: SpellStateDataEffectsIdsJunction;
    // SpellTypeData: SpellTypeData;
    // SpellVariantData: SpellVariantData;
    // SpellVariantData_spellIds_junction: SpellVariantDataSpellIdsJunction;
    // StealthBoneData: StealthBoneData;
    // SubAreaData: SubAreaData;
    // SubAreaData_entranceMapIds_junction: SubAreaDataEntranceMapIdsJunction;
    // SubAreaData_exitMapIds_junction: SubAreaDataExitMapIdsJunction;
    // SubAreaData_mapIds_junction: SubAreaDataMapIdsJunction;
    // SuperAreaData: SuperAreaData;
    // TaxCollectorFirstnameData: TaxCollectorFirstnameData;
    // TaxCollectorNameData: TaxCollectorNameData;
    // TextIconReferenceData: TextIconReferenceData;
    // TitleCategoryData: TitleCategoryData;
    // TitleData: TitleData;
    translations: Translations;
    // VeteranRewardData: VeteranRewardData;
    WaypointData: WaypointData;
    // WeaponData: WeaponData;
    // WeaponData_dropMonsterIds_junction: WeaponDataDropMonsterIdsJunction;
    // WeaponData_dropTemporisMonsterIds_junction: WeaponDataDropTemporisMonsterIdsJunction;
    // WeaponData_evolutiveEffectIds_junction: WeaponDataEvolutiveEffectIdsJunction;
    // WeaponData_recipeIds_junction: WeaponDataRecipeIdsJunction;
    // WorldEventData: WorldEventData;
    // WorldEventDungeonData: WorldEventDungeonData;
    // WorldEventFarmingSimulatorData: WorldEventFarmingSimulatorData;
    // WorldEventMonstersHunterData: WorldEventMonstersHunterData;
    // WorldEventRewardData: WorldEventRewardData;
    // WorldEventWorldBossesData: WorldEventWorldBossesData;
    WorldMapData: WorldMapData;
}
